sforgcompare/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView, RedirectView
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'compareorgs.views.index', name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^job_status/(?P<job_id>[0-9A-Za-z_\-]+)/$', 'compareorgs.views.job_status'),
	url(r'^download_status/(?P<job_id>[0-9A-Za-z_\-]+)/$', 'compareorgs.views.download_status'),
    url(r'^compare_orgs/(?P<job_id>[0-9A-Za-z_\-]+)/$', 'compareorgs.views.compare_orgs'),
    url(r'^compare_result/(?P<job_id>[0-9A-Za-z_\-]+)/$', 'compareorgs.views.compare_results'),
    url(r'^re-run-job/(?P<job_id>[0-9A-Za-z_\-]+)/$', 'compareorgs.views.rerunjob'),
    url(r'^check_file_status/(?P<job_id>[0-9A-Za-z_\-]+)/$', 'compareorgs.views.check_file_status'),
    url(r'^get_metadata/(?P<component_id>\d+)/$', 'compareorgs.views.get_metadata'),
    url(r'^get_diffhtml/(?P<component_id>\d+)/$', 'compareorgs.views.get_diffhtml'),
) + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

compareorgs/forms.py
from django import forms
from suds.client import Client
from django.conf import settings

class JobForm(forms.Form):
	org_one_type = forms.ChoiceField(choices=(('Production', 'Production'),('Sandbox','Sandbox')))
	org_one_username = forms.CharField()
	org_one_password = forms.CharField()
	org_one_session_id = forms.CharField(required=False)
	org_one_metadata_url = forms.CharField(required=False)
	org_one_org_id = forms.CharField(required=False)
	org_one_org_name = forms.CharField(required=False)
	org_two_type = forms.ChoiceField(choices=(('Production', 'Production'),('Sandbox','Sandbox')))
	org_two_username = forms.CharField()
	org_two_password = forms.CharField()
	org_two_session_id = forms.CharField(required=False)
	org_two_metadata_url = forms.CharField(required=False)
	org_two_org_id = forms.CharField(required=False)
	org_two_org_name = forms.CharField(required=False)
	api_choice = forms.ChoiceField(choices=(('metadata', 'Metadata API'),('tooling','Tooling API')))
	contextual_diff = forms.BooleanField(required=False, initial=True)

	def clean(self):

		cleaned_data = super(JobForm, self).clean()

		# Attempt login of Org One
		org_one_login_result = self.login_successful(
			cleaned_data['org_one_type'],
			cleaned_data['org_one_username'],
			cleaned_data['org_one_password']
		)

		if org_one_login_result and org_one_login_result.sessionId:
			cleaned_data['org_one_session_id'] = org_one_login_result.sessionId
			cleaned_data['org_one_metadata_url'] = org_one_login_result.metadataServerUrl
			cleaned_data['org_one_org_id'] = org_one_login_result.userInfo.organizationId
			cleaned_data['org_one_org_name'] = org_one_login_result.userInfo.organizationName
		else:
			raise forms.ValidationError('Error logging into Org One. Please check your username and password and try again.')
		

		# Attempt login of Org One
		org_two_login_result = self.login_successful(
			cleaned_data['org_two_type'],
			cleaned_data['org_two_username'],
			cleaned_data['org_two_password']
		)

		if org_two_login_result and org_two_login_result.sessionId:
			cleaned_data['org_two_session_id'] = org_two_login_result.sessionId
			cleaned_data['org_two_metadata_url'] = org_two_login_result.metadataServerUrl
			cleaned_data['org_two_org_id'] = org_two_login_result.userInfo.organizationId
			cleaned_data['org_two_org_name'] = org_two_login_result.userInfo.organizationName
		else:
			raise forms.ValidationError('Error logging into Org Two. Please check your username and password and try again.')

		return cleaned_data

	def login_successful(self, org_type, username, password):

		# Load WSDL and login
		wsdl = settings.SALESFORCE_PARTNER_PRODUCTION_WSDL if org_type == 'Production' else settings.SALESFORCE_PARTNER_SANDBOX_WSDL
		client = Client(wsdl)

		try:
			login_result = client.service.login(username, password)
			return login_result
		except:
			return None

		

sforgcompare/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>Salesforce.com Org Compare Tool</title>
        <meta name="keywords" content="salesforce, salesforce.com, force.com, compare, merge, sforgcompare" />
        <meta name="description" content="Compare the all metadata between Salesforce Orgs. Useful for seeing missing changes, customisation and building change sets or deployment packages." />
        <meta name="author" content="Ben Edwards (ben@edwards.nz)" />
        <meta charset="UTF-8" />

        <link rel="stylesheet" href="/static/css/bootstrap-3.2.0.min.css">
        <link rel="stylesheet" href="/static/css/styles.css" />
        
        <script type="text/javascript" src="/static/js/jquery-1.10.2.min.js"></script>
        <script type="text/javascript" src="/static/js/bootstrap-3.2.0.min.js"></script>
        {% block scripts %}{% endblock %}
    </head> 

    <body>

        <!-- Static navbar -->
        <nav class="navbar navbar-default">

            <div class="container-fluid">

                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

                <div id="navbar" class="navbar-collapse collapse">

                    <ul class="nav navbar-nav navbar-left">
                        <li>
                            <a href="/" style="padding:5px;">
                                <img src="/static/images/logo-small.png" alt="Org Compare" border="0" />
                            </a>
                        </li>
                        <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
                        <li>
                            <a href="https://cloudtoolkit.co" target="_blank">Salesforce Toolkit</a>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top" style="padding-top:12px;">
                                <input type="hidden" name="cmd" value="_s-xclick" />
                                <input type="hidden" name="hosted_button_id" value="9J3KBL2Q4ZUS4" />
                                <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
                                <img alt="" border="0" src="https://www.paypal.com/en_NZ/i/scr/pixel.gif" width="1" height="1" />
                            </form>
                        </li>
                        <li>
                            <a href="https://github.com/benedwards44/sforgcompare" target="_blank">Source Code</a>
                        </li>
                        <li>
                            <a href="https://twitter.com/benedwards44" target="_blank">@benedwards44</a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="/static/images/i-icon.png" data-toggle="modal" data-target="#infoModal" />
                            </a>
                        </li>
                    </ul>

                </div><!--/.nav-collapse -->

            </div><!--/.container-fluid -->

        </nav>

        <div class="modal fade" id="infoModal" tabindex="-1" role="dialog" aria-labelledby="infoModalLabel" aria-hidden="true">
            <div class="modal-dialog small_dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">
                            <span aria-hidden="true">&times;</span>
                            <span class="sr-only">Close</span>
                        </button>
                        <h3 class="modal-title" id="apiModalLabel">
                            Salesforce Org Compare
                        </h3>
                    </div>
                    <div class="modal-body">
                        <p>
                            For any errors or issues, please feel free to contact me on twitter <a href="https://twitter.com/benedwards44" target="_blank">@benedwards44</a> or via email <a href="mailto:ben@edwards.nz">ben@edwards.nz</a>.
                        </p>
                        <p>
                            I am constantly trying to update and improve this application, as well as other apps I'm working on. Feel free to contact me if you'd like to contribute or have any ideas. All my applications are open sourced on GitHub at <a href="http://github.com/benedwards44" target="_blank">http://github.com/benedwards44</a>.
                        </p>
                        <p>
                            If you haven't already, check out my other apps at the Salesforce Toolkit Page:<br/>
                            <a href="https://cloudtoolkit.co" target="_blank">https://cloudtoolkit.co</a>
                        </p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="clear"></div>

        <div class="col-md-8 col-md-offset-2">
            {% block content %}{% endblock %}
        </div>

    </body>

</html>

sforgcompare/templates/compare_results.html
{% extends 'base.html' %}

{% block scripts %}
<script type="text/javascript" src="/static/js/jquery-migrate-1.1.0.min.js"></script>
<script type="text/javascript" src="/static/jquery-syntaxhighlighter/jquery.syntaxhighlighter.min.js"></script>
<script type="text/javascript" src="/static/js/compare.js"></script>
{% endblock %}

{% block content %}

	<div class="loading-display">

		<div style="float:left;">
			<img src="/static/images/loading.gif" alt="Loading" title="Loading" />
		</div>

		<div style="float:left;margin-left:20px;">
			<h1 style="font-size:1.5em;margin-top:20px;">
				Building results
			</h1>
			<p>
				Shouldn't be long...
			</p>
		</div>

	</div>

	<div id="compare_results">

		<div class="col-md-7">
			<p>
	            Your Org Compare results are presented below. Files are highlighted based on matches or differences. You can click on components to view the file and see highlighted differences within files.
	        </p>
	    </div>

	    <div class="clearfix"></div>

        <hr style="width:100%;margin: 10px 0;" />

        <div class="col-md-5">
	        <select class="form-control" id="display_option">
	            <option value="all">Show All Components</option>
	            <option value="diff" selected="selected">Show Only Differences</option>
	        </select>
	    </div>

	    <div class="col-md-7 text-right">
	        <div id="legend">
	            <div class="alert alert-success legend" role="alert" id="legend_match">
	                Match
	            </div>
	            <div class="alert alert-warning legend" role="alert" id="legend_diff">
	                Diff in file
	            </div>
	            <div class="alert alert-danger legend" role="alert" id="legend_nomatch">
	                New file
	            </div>
	        </div>
	    </div>

        <div style="clear:both;"></div>

		<table class="table table-hover" id="compare_results_table">

			<thead>
				<tr>
					<th><h2>{{ org_left_username }}</h2></th>
					<th><h2>{{ org_right_username }}</h2></th>
				</tr>
			</thead>

			<tbody>
				{% autoescape off %}
					{{ html_rows }}
				{% endautoescape %}
			</tbody>

		</table>

		<div class="alert alert-info" role="alert" id="no_differences_message">
			<p>
				There are no differences between the Orgs selected.
			</p>
		</div>

	</div>

	<div class="modal fade" id="viewCodeModal" tabindex="-1" role="dialog" aria-labelledby="codeModalLabel" aria-hidden="true">
		<div class="modal-dialog">
	    	<div class="modal-content">
	      		<div class="modal-header">
	        		<button type="button" class="close" data-dismiss="modal">
	        			<span aria-hidden="true">&times;</span>
	        			<span class="sr-only">Close</span>
	        		</button>
	        		<h3 class="modal-title" id="codeModalLabel"></h3>
	      		</div>
	      		<div class="modal-body">
	      			<div id="top_scrollbar">
	                    <div id="scrollbar"></div>
	                </div>
	      			<div id="codeModalBody">
	      			</div>
	      		</div>
	      		<div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			    </div>
	    	</div>
	  	</div>
	</div>

	<div class="modal fade" id="downloadOfflineModal" tabindex="-1" role="dialog" aria-labelledby="downloadOfflineModalLabel" aria-hidden="true">
		<div class="modal-dialog">
	    	<div class="modal-content">
	      		<div class="modal-header"></div>
	      		<div class="modal-body"></div>
	      		<div class="modal-footer"></div>
	    	</div>
	  	</div>
	</div>

{% endblock %}

sforgcompare/templates/downloading.html
{% extends 'base.html' %}

{% block content %}

	<h1>Salesforce Org Compare</h1>
	<p>
		This tool uses the Salesforce Tooling or Metadata API (user selection) to compare metadata between two Orgs. This is useful when planning deployments or building deployment packages, as well as seeing what configuration exists in Production to Sandbox or between Sandbox environments.
	</p>
	<p>
		None of your organisation information or data is captured or kept from running this tool.
	</p>

	<div class="alert alert-info" role="alert">
		<p>
			<strong>Note:</strong> If you've selected to be emailed when the job is ready, you can close this window and visit the link in the email.
		</p>
	</div>
	
	<div class="loading-components">

		<br/><br/>

		<div style="float:left;">
			<img src="/static/images/loading.gif" alt="Loading" title="Loading" />
		</div>

		<div style="float:left;margin-left:20px;">
			<h1 style="font-size:1.5em;margin-top:20px;">
				Downloading metadata ...
			</h1>
			<p>
				This can take some time, depending on size of Orgs and API selection.
			</p>
		</div>

	</div>

	<div class="alert alert-danger error" role="alert" style="display:none;">
		<p>
			There was an error processing your request: <i class="error_message"></i>
			<br/><br/>
			Please <a href="/{% if request.GET.noheader == '1' %}?noheader=1{% endif %}">return</a> to the home page and try again.
		</p>
	</div>

	<script>
 		window.setInterval(function () 
 		{
       		$.ajax({
			    url: '/download_status/{{ job.random_id }}',
			    type: 'get', 
			    dataType: 'json',
			    success: function(resp) 
			    {
			        if (resp.status == 'Finished')
			        {
			        	window.location = '/compare_orgs/{{ job.random_id }}/?api={{ job.api_choice }}{% if request.GET.noheader == "1" %}?noheader=1{% endif %}';
			        } 
			        else if (resp.status == 'Error')
			        {
			        	$('.loading-components').hide();
			        	$('.error').show();
			        	$('.error_message').text(resp.error);
			        }
			        // Else job is still running, this will re-run shortly.
			    },
			    failure: function(resp) 
			    { 
			        $('.loading-components').hide();
		        	$('.error').show();
		        	$('.error_message').text(resp);
			    }
			});
    	}, 10000);
	</script>

{% endblock %}

sforgcompare/templates/index.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}

	<h1>Salesforce Org Compare</h1>
	<p>
		This tool uses the Salesforce Tooling or Metadata API (user selection) to compare metadata between two Orgs. This is useful when planning deployments or building deployment packages, as well as seeing what configuration exists in Production to Sandbox or between Sandbox environments.
	</p>
	<p>
		None of your organisation information or data is captured or kept from running this tool.
	</p>
	<div class="alert alert-warning alert-dismissible text-center" role="alert">
		<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		Help keep <strong>Salesforce Org Compare</strong> free! Please donate to support development and Heroku running costs.
		Any value is appreciated!
		<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top" style="padding-top:12px;">
			<input type="hidden" name="cmd" value="_s-xclick" />
			<input type="hidden" name="hosted_button_id" value="9J3KBL2Q4ZUS4" />
			<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
			<img alt="" border="0" src="https://www.paypal.com/en_NZ/i/scr/pixel.gif" width="1" height="1" />
		</form>
	</div>
	<div class="alert alert-info alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		<strong>Note:</strong>
		<ul>
			<li>You will need to be a System Administrator on both Orgs in order to use this application.</li>
			<li>This application uses multiple API calls to your Salesforce Org to retrieve metadata and execute the logic it needs to run. Each Salesforce Org has a 24 hour limit of API calls it can make, and may break other integrations if you exceed this limit.</li>
		</ul>
	</div>

	<form action="." method="POST">

		{% csrf_token %}

		{% if job_form.errors %}
			<div class="alert alert-danger" role="alert">
				{{ job_form.errors }}
			</div>
		{% endif %}

		

		<div class="left-half">

			<h2>Org One</h2>

			<table id="orgOneLogin">

				<tr>
					<td width="200">
						{% render_field job_form.org_one_type placeholder="Username" class="form-control" %}
					</td>
				</tr>
				<tr>
					<td>
						{% render_field job_form.org_one_username placeholder="Username" class="form-control" %}
					</td>
				</tr>
				<tr>
					<td>
						{% render_field job_form.org_one_password placeholder="Password + Security Token" class="form-control" %}
					</td>
				</tr>

			</table>

		</div>

		<div class="right-half">

			<h2>Org Two</h2>

			<table id="orgTwoLogin">

				<tr>
					<td width="200">
						{% render_field job_form.org_two_type placeholder="Username" class="form-control" %}
					</td>
				</tr>
				<tr>
					<td>
						{% render_field job_form.org_two_username placeholder="Username" class="form-control" %}
					</td>
				</tr>
				<tr>
					<td>
						{% render_field job_form.org_two_password placeholder="Password + Security Token" class="form-control" %}
					</td>
				</tr>

			</table>

		</div>

		<div class="clear"></div>

		<div id="compareOrgs">

			{% render_field job_form.api_choice class="form-control" %}

			<img src="/static/images/i-icon.png" class="info_icon" data-toggle="modal" data-target="#apiModal" />

			<div style="clear:both;margin: 5px 0;"></div>

			<input type="checkbox" id="id_contextual_diff" name="contextual_diff" class="form-control" checked="checked" />
			<label id="id_contextual_diff_label" for="id_contextual_diff">Contextual Diff</label>
			<img src="/static/images/i-icon.png" class="info_icon" data-toggle="modal" data-target="#contextModal" style="margin-left:60px;" />

			<div style="clear:both;margin: 5px 0;"></div>

			<input type="submit" id="submitCompare" value="Compare Orgs" />

			<br/><br/>
		</div>

	</form>

	<div class="modal fade" id="apiModal" tabindex="-1" role="dialog" aria-labelledby="apiModalLabel" aria-hidden="true">
		<div class="modal-dialog small_dialog">
	    	<div class="modal-content">
	      		<div class="modal-header">
	        		<button type="button" class="close" data-dismiss="modal">
	        			<span aria-hidden="true">&times;</span>
	        			<span class="sr-only">Close</span>
	        		</button>
	        		<h3 class="modal-title" id="apiModalLabel">
	        			API Selection
	        		</h3>
	      		</div>
	      		<div class="modal-body">
	        		<h4>
	        			Tooling API
	        		</h4>
	        		<p>
	        			The Tooling API is much faster in querying the metadata and will return the org compare results a lot faster. However, the Tooling API currently only supports code-based metadata, so is limited to the <a href="#" data-toggle="popover" title="Supported Metadata" data-content="ApexClass <br/>ApexComponent<br/>ApexPage<br/>ApexTrigger" data-html="true" data-trigger="focus">following types of metadata</a>.
	        		</p>

	        		<br/>

	        		<h4>
	        			Metadata API
	        		</h4>
	        		<p>
	        			The Metadata API is slower but returns the full set of queryable metadata for your Org. Use the Metadata API if there are components not contained in the Tooling API that you would like to compare. This should be used if you want a true <strong>full</strong> comparison between two Orgs.
	        			<br/><br/>
	        			Note: The Metadata API is limited to 5,000 files retrieved in a single call.
	        		</p>
	      		</div>
	      		<div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			    </div>
	    	</div>
	  	</div>
	</div>

	<div class="modal fade" id="emailModal" tabindex="-1" role="dialog" aria-labelledby="emailModalLabel" aria-hidden="true">
		<div class="modal-dialog small_dialog">
	    	<div class="modal-content">
	      		<div class="modal-header">
	        		<button type="button" class="close" data-dismiss="modal">
	        			<span aria-hidden="true">&times;</span>
	        			<span class="sr-only">Close</span>
	        		</button>
	        		<h3 class="modal-title" id="emailModalLabel">
	        			Email Me
	        		</h3>
	      		</div>
	      		<div class="modal-body">
	        		<p>
	        			For large Orgs, sometimes the process can take some time. If you'd rather do something else instead of staring at an orange loading circle then we can email you a link when the job is done so you can view your results.
	        			<br/><br/>
	        			Note: Because we don't want to store your metadata, the link will only be valid for an hour after the job is done. Once you've viewed your results, we clear all stored information.
	        		</p>
	      		</div>
	      		<div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			    </div>
	    	</div>
	  	</div>
	</div>

	<div class="modal fade" id="contextModal" tabindex="-1" role="dialog" aria-labelledby="contextModalLabel" aria-hidden="true">
		<div class="modal-dialog small_dialog">
	    	<div class="modal-content">
	      		<div class="modal-header">
	        		<button type="button" class="close" data-dismiss="modal">
	        			<span aria-hidden="true">&times;</span>
	        			<span class="sr-only">Close</span>
	        		</button>
	        		<h3 class="modal-title" id="emailModalLabel">
	        			Contextual Diff
	        		</h3>
	      		</div>
	      		<div class="modal-body">
	        		<p>
	        			Choose this option to enable a contextual diff. A contextual diff means that compare results will only show the lines of metadata that are deemed to be different, and a number of lines before and after. 
	        			<br/><br/>
	        			This is preferable for large files, as it will only show what is relevant, rather than the entire file.
	        		</p>
	      		</div>
	      		<div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			    </div>
	    	</div>
	  	</div>
	</div>

{% endblock %}

sforgcompare/templates/loading.html
{% extends 'base.html' %}

{% block content %}

	<h1>Salesforce Org Compare</h1>
	<p>
		This tool uses the Salesforce Tooling or Metadata API (user selection) to compare metadata between two Orgs. This is useful when planning deployments or building deployment packages, as well as seeing what configuration exists in Production to Sandbox or between Sandbox environments.
	</p>
	<p>
		None of your organisation information or data is captured or kept from running this tool.
	</p>

	<div class="alert alert-info" role="alert">
		<p>
			<strong>Note:</strong> If you've selected to be emailed when the job is ready, you can close this window and visit the link in the email.
		</p>
	</div>
	
	<div class="loading-components">

		<br/><br/>

		<div style="float:left;">
			<img src="/static/images/loading.gif" alt="Loading" title="Loading" />
		</div>

		<div style="float:left;margin-left:20px;">
			<h1 style="font-size:1.5em;margin-top:20px;">
				Querying all metadata and comparing...
			</h1>
			<p>
				This can take some time, depending on size of Orgs and API selection.
			</p>
		</div>

	</div>

	<div class="alert alert-danger error" role="alert" style="display:none;">
		<p>
			There was an error processing your request: <i class="error_message"></i>
			<br/><br/>
			Please <a href="/{% if request.GET.noheader == '1' %}?noheader=1{% endif %}">return</a> to the home page and try again.
		</p>
	</div>

	<script>
 		window.setInterval(function () 
 		{
       		$.ajax({
			    url: '/job_status/{{ job.random_id }}',
			    type: 'get', 
			    dataType: 'json',
			    success: function(resp) 
			    {
			        if (resp.status == 'Finished')
			        {
			        	window.location = '/compare_result/{{ job.random_id }}/{% if request.GET.noheader == "1" %}?noheader=1{% endif %}';
			        } 
			        else if (resp.status == 'Error')
			        {
			        	$('.loading-components').hide();
			        	$('.error').show();
			        	$('.error_message').text(resp.error);
			        }
			        // Else job is still running, this will re-run shortly.
			    },
			    failure: function(resp) 
			    { 
			        $('.loading-components').hide();
		        	$('.error').show();
		        	$('.error_message').text(resp);
			    }
			});
    	}, 10000);
	</script>

{% endblock %}